### ISSUE TITLE
DOMNesting issue with MUI

### ISSUE THREAD

**Issue by yingliucreates** [yingliucreates/google-books-search-api#7]
act_devtools_backend.js:2655 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>.
    at tr
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableRow (http://localhost:3000/static/js/bundle.js:17317:82)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Paper (http://localhost:3000/static/js/bundle.js:13683:83)
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableHead (http://localhost:3000/static/js/bundle.js:16539:82)
    at table
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Table (http://localhost:3000/static/js/bundle.js:15655:82)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Paper (http://localhost:3000/static/js/bundle.js:13683:83)
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableContainer (http://localhost:3000/static/js/bundle.js:16271:82)
    at List (http://localhost:3000/static/js/bundle.js:531:5)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Box (http://localhost:3000/static/js/bundle.js:20886:72)
    at Container (http://localhost:3000/static/js/bundle.js:114:74)
    at div
    at App
    at StyledEngineProvider (http://localhost:3000/static/js/bundle.js:20064:5)
overrideMethod @ react_devtools_backend.js:2655
printWarning @ bundle.js:32275
error @ bundle.js:32252
validateDOMNesting @ bundle.js:41722
createInstance @ bundle.js:41799
completeWork @ bundle.js:51427
completeUnitOfWork @ bundle.js:55189
performUnitOfWork @ bundle.js:55165
workLoopSync @ bundle.js:55079
renderRootSync @ bundle.js:55052
performConcurrentWorkOnRoot @ bundle.js:54446
workLoop @ bundle.js:64643
flushWork @ bundle.js:64621
performWorkUntilDeadline @ bundle.js:64858
react_devtools_backend.js:2655 Warning: validateDOMNesting(...): <div> cannot appear as a child of <table>.
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Paper (http://localhost:3000/static/js/bundle.js:13683:83)
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableHead (http://localhost:3000/static/js/bundle.js:16539:82)
    at table
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Table (http://localhost:3000/static/js/bundle.js:15655:82)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Paper (http://localhost:3000/static/js/bundle.js:13683:83)
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableContainer (http://localhost:3000/static/js/bundle.js:16271:82)
    at List (http://localhost:3000/static/js/bundle.js:531:5)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Box (http://localhost:3000/static/js/bundle.js:20886:72)
    at Container (http://localhost:3000/static/js/bundle.js:114:74)
    at div
    at App
    at StyledEngineProvider (http://localhost:3000/static/js/bundle.js:20064:5)
overrideMethod @ react_devtools_backend.js:2655
printWarning @ bundle.js:32275
error @ bundle.js:32252
validateDOMNesting @ bundle.js:41722
createInstance @ bundle.js:41799
completeWork @ bundle.js:51427
completeUnitOfWork @ bundle.js:55189
performUnitOfWork @ bundle.js:55165
workLoopSync @ bundle.js:55079
renderRootSync @ bundle.js:55052
performConcurrentWorkOnRoot @ bundle.js:54446
workLoop @ bundle.js:64643
flushWork @ bundle.js:64621
performWorkUntilDeadline @ bundle.js:64858
react_devtools_backend.js:2655 Warning: validateDOMNesting(...): <th> cannot appear as a child of <div>.
    at th
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableCell (http://localhost:3000/static/js/bundle.js:16077:83)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Paper (http://localhost:3000/static/js/bundle.js:13683:83)
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableRow (http://localhost:3000/static/js/bundle.js:17317:82)
    at tbody
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableBody (http://localhost:3000/static/js/bundle.js:15871:82)
    at table
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Table (http://localhost:3000/static/js/bundle.js:15655:82)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Paper (http://localhost:3000/static/js/bundle.js:13683:83)
    at http://localhost:3000/static/js/bundle.js:1666:66
    at TableContainer (http://localhost:3000/static/js/bundle.js:16271:82)
    at List (http://localhost:3000/static/js/bundle.js:531:5)
    at div
    at http://localhost:3000/static/js/bundle.js:1666:66
    at Box (http://localhost:3000/static/js/bundle.js:20886:72)
    at Container (http://localhost:3000/static/js/bundle.js:114:74)
    at div
    at App
    at StyledEngineProvider (http://localhost:3000/static/js/bundle.js:20064:5)
overrideMethod @ react_devtools_backend.js:2655
printWarning @ bundle.js:32275
error @ bundle.js:32252
validateDOMNesting @ bundle.js:41722
createInstance @ bundle.js:41799
completeWork @ bundle.js:51427
completeUnitOfWork @ bundle.js:55189
performUnitOfWork @ bundle.js:55165
workLoopSync @ bundle.js:55079
renderRootSync @ bundle.js:55052
performConcurrentWorkOnRoot @ bundle.js:54446
workLoop @ bundle.js:64643
flushWork @ bundle.js:64621
performWorkUntilDeadline @ bundle.js:64858
re

**Comment by yingliucreates** [comment]
Refactored <div> in App to <Box> from MUI
